# Generated by Django 5.2 on 2025-05-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_remove_event_category_remove_tickettype_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
