# Generated by Django 5.2 on 2025-05-07 14:37

import django.core.validators
import django.db.models.deletion
import games.models
import games.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('views', models.PositiveIntegerField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(upload_to='game_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('game_file', models.FileField(upload_to=games.models.game_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'exe', 'apk', 'rar']), games.validators.validate_file_size])),
                ('sets', models.JSONField(blank=True, default=list)),
                ('dev_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.devteam')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.genre')),
                ('platforms', models.ManyToManyField(related_name='games', to='games.platform')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='games.tag')),
            ],
        ),
    ]
