# Generated by Django 5.2 on 2025-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dev_team',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='DevTeam',
        ),
    ]
