# Generated by Django 5.2 on 2025-05-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_dev_team_delete_devteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sets',
        ),
    ]
