# Generated by Django 5.2 on 2025-05-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
