# Generated by Django 5.2 on 2025-05-07 17:11

import django.core.validators
import games.models
import games.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_genre_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(upload_to=games.models.game_file_upload_to, validators=[django.core.validators.FileExtensionValidator(['zip', 'exe', 'apk', 'rar']), games.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to=games.models.game_file_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
